# Spring
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: TRUE
    hibernate:
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mvc:
    hidden-method:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  # Vault
  active:
    profile: dev
  application:
    name: techstore
  cloud:
    vault:
      uri: http://127.0.0.1:8200
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
  config:
    import: vault://
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/tech_store?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  # Resources
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
# Server
server:
  error:
    whitelabel:
      enabled: off
    include-message: always
    include-stacktrace: always
  port: 8080
logging:
  level:
    web: DEBUG
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN