INSERT IGNORE INTO `countries` (`name`,`abv`,`abv3`,`abv3_alt`,`code`,`slug`,`uuid`)
VALUES
    ('Afghanistan','AF','AFG',NULL,4,'afghanistan',UUID()),
    ('Aland Islands','AX','ALA',NULL,248,'aland-islands',UUID()),
    ('Albania','AL','ALB',NULL,8,'albania',UUID()),
    ('Algeria','DZ','DZA',NULL,12,'algeria',UUID()),
    ('American Samoa','AS','ASM',NULL,16,'american-samoa',UUID()),
    ('Andorra','AD','AND',NULL,20,'andorra',UUID()),
    ('Angola','AO','AGO',NULL,24,'angola',UUID()),
    ('Anguilla','AI','AIA',NULL,660,'anguilla',UUID()),
    ('Antigua and Barbuda','AG','ATG',NULL,28,'antigua-and-barbuda',UUID()),
    ('Argentina','AR','ARG',NULL,32,'argentina',UUID()),
    ('Armenia','AM','ARM',NULL,51,'armenia',UUID()),
    ('Aruba','AW','ABW',NULL,533,'aruba',UUID()),
    ('Australia','AU','AUS',NULL,36,'australia',UUID()),
    ('Austria','AT','AUT',NULL,40,'austria',UUID()),
    ('Azerbaijan','AZ','AZE',NULL,31,'azerbaijan',UUID()),
    ('Bahamas','BS','BHS',NULL,44,'bahamas',UUID()),
    ('Bahrain','BH','BHR',NULL,48,'bahrain',UUID()),
    ('Bangladesh','BD','BGD',NULL,50,'bangladesh',UUID()),
    ('Barbados','BB','BRB',NULL,52,'barbados',UUID()),
    ('Belarus','BY','BLR',NULL,112,'belarus',UUID()),
    ('Belgium','BE','BEL',NULL,56,'belgium',UUID()),
    ('Belize','BZ','BLZ',NULL,84,'belize',UUID()),
    ('Benin','BJ','BEN',NULL,204,'benin',UUID()),
    ('Bermuda','BM','BMU',NULL,60,'bermuda',UUID()),
    ('Bhutan','BT','BTN',NULL,64,'bhutan',UUID()),
    ('Bolivia','BO','BOL',NULL,68,'bolivia',UUID()),
    ('Bosnia and Herzegovina','BA','BIH',NULL,70,'bosnia-and-herzegovina',UUID()),
    ('Botswana','BW','BWA',NULL,72,'botswana',UUID()),
    ('Brazil','BR','BRA',NULL,76,'brazil',UUID()),
    ('British Virgin Islands','VG','VGB',NULL,92,'british-virgin-islands',UUID()),
    ('Brunei Darussalam','BN','BRN',NULL,96,'brunei-darussalam',UUID()),
    ('Bulgaria','BG','BGR',NULL,100,'bulgaria',UUID()),
    ('Burkina Faso','BF','BFA',NULL,854,'burkina-faso',UUID()),
    ('Burundi','BI','BDI',NULL,108,'burundi',UUID()),
    ('Cambodia','KH','KHM',NULL,116,'cambodia',UUID()),
    ('Cameroon','CM','CMR',NULL,120,'cameroon',UUID()),
    ('Canada','CA','CAN',NULL,124,'canada',UUID()),
    ('Cape Verde','CV','CPV',NULL,132,'cape-verde',UUID()),
    ('Cayman Islands','KY','CYM',NULL,136,'cayman-islands',UUID()),
    ('Central African Republic','CF','CAF',NULL,140,'central-african-republic',UUID()),
    ('Chad','TD','TCD',NULL,148,'chad',UUID()),
    ('Chile','CL','CHL','CHI',152,'chile',UUID()),
    ('China','CN','CHN',NULL,156,'china',UUID()),
    ('Colombia','CO','COL',NULL,170,'colombia',UUID()),
    ('Comoros','KM','COM',NULL,174,'comoros',UUID()),
    ('Congo','CG','COG',NULL,178,'congo',UUID()),
    ('Cook Islands','CK','COK',NULL,184,'cook-islands',UUID()),
    ('Costa Rica','CR','CRI',NULL,188,'costa-rica',UUID()),
    ('Cote d\'Ivoire','CI','CIV',NULL,384,'cote-divoire',UUID()),
    ('Croatia','HR','HRV',NULL,191,'croatia',UUID()),
    ('Cuba','CU','CUB',NULL,192,'cuba',UUID()),
    ('Cyprus','CY','CYP',NULL,196,'cyprus',UUID()),
    ('Czech Republic','CZ','CZE',NULL,203,'czech-republic',UUID()),
    ('Democratic Republic of the Congo','CD','COD',NULL,180,'democratic-republic-of-congo',UUID()),
    ('Denmark','DK','DNK',NULL,208,'denmark',UUID()),
    ('Djibouti','DJ','DJI',NULL,262,'djibouti',UUID()),
    ('Dominica','DM','DMA',NULL,212,'dominica',UUID()),
    ('Dominican Republic','DO','DOM',NULL,214,'dominican-republic',UUID()),
    ('Ecuador','EC','ECU',NULL,218,'ecuador',UUID()),
    ('Egypt','EG','EGY',NULL,818,'egypt',UUID()),
    ('El Salvador','SV','SLV',NULL,222,'el-salvador',UUID()),
    ('Equatorial Guinea','GQ','GNQ',NULL,226,'equatorial-guinea',UUID()),
    ('Eritrea','ER','ERI',NULL,232,'eritrea',UUID()),
    ('Estonia','EE','EST',NULL,233,'estonia',UUID()),
    ('Ethiopia','ET','ETH',NULL,231,'ethiopia',UUID()),
    ('Faeroe Islands','FO','FRO',NULL,234,'faeroe-islands',UUID()),
    ('Falkland Islands','FK','FLK',NULL,238,'falkland-islands',UUID()),
    ('Fiji','FJ','FJI',NULL,242,'fiji',UUID()),
    ('Finland','FI','FIN',NULL,246,'finland',UUID()),
    ('France','FR','FRA',NULL,250,'france',UUID()),
    ('French Guiana','GF','GUF',NULL,254,'french-guiana',UUID()),
    ('French Polynesia','PF','PYF',NULL,258,'french-polynesia',UUID()),
    ('Gabon','GA','GAB',NULL,266,'gabon',UUID()),
    ('Gambia','GM','GMB',NULL,270,'gambia',UUID()),
    ('Georgia','GE','GEO',NULL,268,'georgia',UUID()),
    ('Germany','DE','DEU',NULL,276,'germany',UUID()),
    ('Ghana','GH','GHA',NULL,288,'ghana',UUID()),
    ('Gibraltar','GI','GIB',NULL,292,'gibraltar',UUID()),
    ('Greece','GR','GRC',NULL,300,'greece',UUID()),
    ('Greenland','GL','GRL',NULL,304,'greenland',UUID()),
    ('Grenada','GD','GRD',NULL,308,'grenada',UUID()),
    ('Guadeloupe','GP','GLP',NULL,312,'guadeloupe',UUID()),
    ('Guam','GU','GUM',NULL,316,'guam',UUID()),
    ('Guatemala','GT','GTM',NULL,320,'guatemala',UUID()),
    ('Guernsey','GG','GGY',NULL,831,'guernsey',UUID()),
    ('Guinea','GN','GIN',NULL,324,'guinea',UUID()),
    ('Guinea-Bissau','GW','GNB',NULL,624,'guinea-bissau',UUID()),
    ('Guyana','GY','GUY',NULL,328,'guyana',UUID()),
    ('Haiti','HT','HTI',NULL,332,'haiti',UUID()),
    ('Holy See','VA','VAT',NULL,336,'holy-see',UUID()),
    ('Honduras','HN','HND',NULL,340,'honduras',UUID()),
    ('Hong Kong','HK','HKG',NULL,344,'hong-kong',UUID()),
    ('Hungary','HU','HUN',NULL,348,'hungary',UUID()),
    ('Iceland','IS','ISL',NULL,352,'iceland',UUID()),
    ('India','IN','IND',NULL,356,'india',UUID()),
    ('Indonesia','ID','IDN',NULL,360,'indonesia',UUID()),
    ('Iran','IR','IRN',NULL,364,'iran',UUID()),
    ('Iraq','IQ','IRQ',NULL,368,'iraq',UUID()),
    ('Ireland','IE','IRL',NULL,372,'ireland',UUID()),
    ('Isle of Man','IM','IMN',NULL,833,'isle-of-man',UUID()),
    ('Israel','IL','ISR',NULL,376,'israel',UUID()),
    ('Italy','IT','ITA',NULL,380,'italy',UUID()),
    ('Jamaica','JM','JAM',NULL,388,'jamaica',UUID()),
    ('Japan','JP','JPN',NULL,392,'japan',UUID()),
    ('Jersey','JE','JEY',NULL,832,'jersey',UUID()),
    ('Jordan','JO','JOR',NULL,400,'jordan',UUID()),
    ('Kazakhstan','KZ','KAZ',NULL,398,'kazakhstan',UUID()),
    ('Kenya','KE','KEN',NULL,404,'kenya',UUID()),
    ('Kiribati','KI','KIR',NULL,296,'kiribati',UUID()),
    ('Kuwait','KW','KWT',NULL,414,'kuwait',UUID()),
    ('Kyrgyzstan','KG','KGZ',NULL,417,'kyrgyzstan',UUID()),
    ('Laos','LA','LAO',NULL,418,'laos',UUID()),
    ('Latvia','LV','LVA',NULL,428,'latvia',UUID()),
    ('Lebanon','LB','LBN',NULL,422,'lebanon',UUID()),
    ('Lesotho','LS','LSO',NULL,426,'lesotho',UUID()),
    ('Liberia','LR','LBR',NULL,430,'liberia',UUID()),
    ('Libyan Arab Jamahiriya','LY','LBY',NULL,434,'libyan-arab-jamahiriya',UUID()),
    ('Liechtenstein','LI','LIE',NULL,438,'liechtenstein',UUID()),
    ('Lithuania','LT','LTU',NULL,440,'lithuania',UUID()),
    ('Luxembourg','LU','LUX',NULL,442,'luxembourg',UUID()),
    ('Macao','MO','MAC',NULL,446,'macao',UUID()),
    ('Macedonia','MK','MKD',NULL,807,'macedonia',UUID()),
    ('Madagascar','MG','MDG',NULL,450,'madagascar',UUID()),
    ('Malawi','MW','MWI',NULL,454,'malawi',UUID()),
    ('Malaysia','MY','MYS',NULL,458,'malaysia',UUID()),
    ('Maldives','MV','MDV',NULL,462,'maldives',UUID()),
    ('Mali','ML','MLI',NULL,466,'mali',UUID()),
    ('Malta','MT','MLT',NULL,470,'malta',UUID()),
    ('Marshall Islands','MH','MHL',NULL,584,'marshall-islands',UUID()),
    ('Martinique','MQ','MTQ',NULL,474,'martinique',UUID()),
    ('Mauritania','MR','MRT',NULL,478,'mauritania',UUID()),
    ('Mauritius','MU','MUS',NULL,480,'mauritius',UUID()),
    ('Mayotte','YT','MYT',NULL,175,'mayotte',UUID()),
    ('Mexico','MX','MEX',NULL,484,'mexico',UUID()),
    ('Micronesia','FM','FSM',NULL,583,'micronesia',UUID()),
    ('Moldova','MD','MDA',NULL,498,'moldova',UUID()),
    ('Monaco','MC','MCO',NULL,492,'monaco',UUID()),
    ('Mongolia','MN','MNG',NULL,496,'mongolia',UUID()),
    ('Montenegro','ME','MNE',NULL,499,'montenegro',UUID()),
    ('Montserrat','MS','MSR',NULL,500,'montserrat',UUID()),
    ('Morocco','MA','MAR',NULL,504,'morocco',UUID()),
    ('Mozambique','MZ','MOZ',NULL,508,'mozambique',UUID()),
    ('Myanmar','MM','MMR','BUR',104,'myanmar',UUID()),
    ('Namibia','NA','NAM',NULL,516,'namibia',UUID()),
    ('Nauru','NR','NRU',NULL,520,'nauru',UUID()),
    ('Nepal','NP','NPL',NULL,524,'nepal',UUID()),
    ('Netherlands','NL','NLD',NULL,528,'netherlands',UUID()),
    ('Netherlands Antilles','AN','ANT',NULL,530,'netherlands-antilles',UUID()),
    ('New Caledonia','NC','NCL',NULL,540,'new-caledonia',UUID()),
    ('New Zealand','NZ','NZL',NULL,554,'new-zealand',UUID()),
    ('Nicaragua','NI','NIC',NULL,558,'nicaragua',UUID()),
    ('Niger','NE','NER',NULL,562,'niger',UUID()),
    ('Nigeria','NG','NGA',NULL,566,'nigeria',UUID()),
    ('Niue','NU','NIU',NULL,570,'niue',UUID()),
    ('Norfolk Island','NF','NFK',NULL,574,'norfolk-island',UUID()),
    ('North Korea','KP','PRK',NULL,408,'north-korea',UUID()),
    ('Northern Mariana Islands','MP','MNP',NULL,580,'northern-mariana-islands',UUID()),
    ('Norway','NO','NOR',NULL,578,'norway',UUID()),
    ('Oman','OM','OMN',NULL,512,'oman',UUID()),
    ('Pakistan','PK','PAK',NULL,586,'pakistan',UUID()),
    ('Palau','PW','PLW',NULL,585,'palau',UUID()),
    ('Palestine','PS','PSE',NULL,275,'palestine',UUID()),
    ('Panama','PA','PAN',NULL,591,'panama',UUID()),
    ('Papua New Guinea','PG','PNG',NULL,598,'papua-new-guinea',UUID()),
    ('Paraguay','PY','PRY',NULL,600,'paraguay',UUID()),
    ('Peru','PE','PER',NULL,604,'peru',UUID()),
    ('Philippines','PH','PHL',NULL,608,'philippines',UUID()),
    ('Pitcairn','PN','PCN',NULL,612,'pitcairn',UUID()),
    ('Poland','PL','POL',NULL,616,'poland',UUID()),
    ('Portugal','PT','PRT',NULL,620,'portugal',UUID()),
    ('Puerto Rico','PR','PRI',NULL,630,'puerto-rico',UUID()),
    ('Qatar','QA','QAT',NULL,634,'qatar',UUID()),
    ('Reunion','RE','REU',NULL,638,'reunion',UUID()),
    ('Romania','RO','ROU','ROM',642,'romania',UUID()),
    ('Russian Federation','RU','RUS',NULL,643,'russian-federation',UUID()),
    ('Rwanda','RW','RWA',NULL,646,'rwanda',UUID()),
    ('Saint Helena','SH','SHN',NULL,654,'saint-helena',UUID()),
    ('Saint Kitts and Nevis','KN','KNA',NULL,659,'saint-kitts-and-nevis',UUID()),
    ('Saint Lucia','LC','LCA',NULL,662,'saint-lucia',UUID()),
    ('Saint Pierre and Miquelon','PM','SPM',NULL,666,'saint-pierre-and-miquelon',UUID()),
    ('Saint Vincent and the Grenadines','VC','VCT',NULL,670,'saint-vincent-and-grenadines',UUID()),
    ('Saint-Barthelemy','BL','BLM',NULL,652,'saint-barthelemy',UUID()),
    ('Saint-Martin','MF','MAF',NULL,663,'saint-martin',UUID()),
    ('Samoa','WS','WSM',NULL,882,'samoa',UUID()),
    ('San Marino','SM','SMR',NULL,674,'san-marino',UUID()),
    ('Sao Tome and Principe','ST','STP',NULL,678,'sao-tome-and-principe',UUID()),
    ('Saudi Arabia','SA','SAU',NULL,682,'saudi-arabia',UUID()),
    ('Senegal','SN','SEN',NULL,686,'senegal',UUID()),
    ('Serbia','RS','SRB',NULL,688,'serbia',UUID()),
    ('Seychelles','SC','SYC',NULL,690,'seychelles',UUID()),
    ('Sierra Leone','SL','SLE',NULL,694,'sierra-leone',UUID()),
    ('Singapore','SG','SGP',NULL,702,'singapore',UUID()),
    ('Slovakia','SK','SVK',NULL,703,'slovakia',UUID()),
    ('Slovenia','SI','SVN',NULL,705,'slovenia',UUID()),
    ('Solomon Islands','SB','SLB',NULL,90,'solomon-islands',UUID()),
    ('Somalia','SO','SOM',NULL,706,'somalia',UUID()),
    ('South Africa','ZA','ZAF',NULL,710,'south-africa',UUID()),
    ('South Korea','KR','KOR',NULL,410,'south-korea',UUID()),
    ('South Sudan','SS','SSD',NULL,728,'south-sudan',UUID()),
    ('Spain','ES','ESP',NULL,724,'spain',UUID()),
    ('Sri Lanka','LK','LKA',NULL,144,'sri-lanka',UUID()),
    ('Sudan','SD','SDN',NULL,729,'sudan',UUID()),
    ('Suriname','SR','SUR',NULL,740,'suriname',UUID()),
    ('Svalbard and Jan Mayen Islands','SJ','SJM',NULL,744,'svalbard-and-jan-mayen-islands',UUID()),
    ('Swaziland','SZ','SWZ',NULL,748,'swaziland',UUID()),
    ('Sweden','SE','SWE',NULL,752,'sweden',UUID()),
    ('Switzerland','CH','CHE',NULL,756,'switzerland',UUID()),
    ('Syrian Arab Republic','SY','SYR',NULL,760,'syrian-arab-republic',UUID()),
    ('Tajikistan','TJ','TJK',NULL,762,'tajikistan',UUID()),
    ('Tanzania','TZ','TZA',NULL,834,'tanzania',UUID()),
    ('Thailand','TH','THA',NULL,764,'thailand',UUID()),
    ('Timor-Leste','TP','TLS',NULL,626,'timor-leste',UUID()),
    ('Togo','TG','TGO',NULL,768,'togo',UUID()),
    ('Tokelau','TK','TKL',NULL,772,'tokelau',UUID()),
    ('Tonga','TO','TON',NULL,776,'tonga',UUID()),
    ('Trinidad and Tobago','TT','TTO',NULL,780,'trinidad-and-tobago',UUID()),
    ('Tunisia','TN','TUN',NULL,788,'tunisia',UUID()),
    ('Turkey','TR','TUR',NULL,792,'turkey',UUID()),
    ('Turkmenistan','TM','TKM',NULL,795,'turkmenistan',UUID()),
    ('Turks and Caicos Islands','TC','TCA',NULL,796,'turks-and-caicos-islands',UUID()),
    ('Tuvalu','TV','TUV',NULL,798,'tuvalu',UUID()),
    ('U.S. Virgin Islands','VI','VIR',NULL,850,'us-virgin-islands',UUID()),
    ('Uganda','UG','UGA',NULL,800,'uganda',UUID()),
    ('Ukraine','UA','UKR',NULL,804,'ukraine',UUID()),
    ('United Arab Emirates','AE','ARE',NULL,784,'united-arab-emirates',UUID()),
    ('United Kingdom','UK','GBR',NULL,826,'united-kingdom',UUID()),
    ('United States','US','USA',NULL,840,'united-states',UUID()),
    ('Uruguay','UY','URY',NULL,858,'uruguay',UUID()),
    ('Uzbekistan','UZ','UZB',NULL,860,'uzbekistan',UUID()),
    ('Vanuatu','VU','VUT',NULL,548,'vanuatu',UUID()),
    ('Venezuela','VE','VEN',NULL,862,'venezuela',UUID()),
    ('Viet Nam','VN','VNM',NULL,704,'viet-nam',UUID()),
    ('Wallis and Futuna Islands','WF','WLF',NULL,876,'wallis-and-futuna-islands',UUID()),
    ('Western Sahara','EH','ESH',NULL,732,'western-sahara',UUID()),
    ('Yemen','YE','YEM',NULL,887,'yemen',UUID()),
    ('Zambia','ZM','ZMB',NULL,894,'zambia',UUID()),
    ('Zimbabwe','ZW','ZWE',NULL,716,'zimbabwe',UUID());