INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Afghanistan','AF','AFG',NULL,4,'afghanistan',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Aland Islands','AX','ALA',NULL,248,'aland-islands',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Albania','AL','ALB',NULL,8,'albania',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Algeria','DZ','DZA',NULL,12,'algeria',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('American Samoa','AS','ASM',NULL,16,'american-samoa',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Andorra','AD','AND',NULL,20,'andorra',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Angola','AO','AGO',NULL,24,'angola',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Anguilla','AI','AIA',NULL,660,'anguilla',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Antigua and Barbuda','AG','ATG',NULL,28,'antigua-and-barbuda',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Argentina','AR','ARG',NULL,32,'argentina',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Armenia','AM','ARM',NULL,51,'armenia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Aruba','AW','ABW',NULL,533,'aruba',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Australia','AU','AUS',NULL,36,'australia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Austria','AT','AUT',NULL,40,'austria',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Azerbaijan','AZ','AZE',NULL,31,'azerbaijan',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Bahamas','BS','BHS',NULL,44,'bahamas',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Bahrain','BH','BHR',NULL,48,'bahrain',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Bangladesh','BD','BGD',NULL,50,'bangladesh',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Barbados','BB','BRB',NULL,52,'barbados',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Belarus','BY','BLR',NULL,112,'belarus',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Belgium','BE','BEL',NULL,56,'belgium',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Belize','BZ','BLZ',NULL,84,'belize',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Benin','BJ','BEN',NULL,204,'benin',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Bermuda','BM','BMU',NULL,60,'bermuda',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Bhutan','BT','BTN',NULL,64,'bhutan',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Bolivia','BO','BOL',NULL,68,'bolivia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Bosnia and Herzegovina','BA','BIH',NULL,70,'bosnia-and-herzegovina',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Botswana','BW','BWA',NULL,72,'botswana',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Brazil','BR','BRA',NULL,76,'brazil',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('British Virgin Islands','VG','VGB',NULL,92,'british-virgin-islands',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Brunei Darussalam','BN','BRN',NULL,96,'brunei-darussalam',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Bulgaria','BG','BGR',NULL,100,'bulgaria',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Burkina Faso','BF','BFA',NULL,854,'burkina-faso',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Burundi','BI','BDI',NULL,108,'burundi',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Cambodia','KH','KHM',NULL,116,'cambodia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Cameroon','CM','CMR',NULL,120,'cameroon',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Canada','CA','CAN',NULL,124,'canada',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Cape Verde','CV','CPV',NULL,132,'cape-verde',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Cayman Islands','KY','CYM',NULL,136,'cayman-islands',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Central African Republic','CF','CAF',NULL,140,'central-african-republic',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Chad','TD','TCD',NULL,148,'chad',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Chile','CL','CHL','CHI',152,'chile',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('China','CN','CHN',NULL,156,'china',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Colombia','CO','COL',NULL,170,'colombia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Comoros','KM','COM',NULL,174,'comoros',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Congo','CG','COG',NULL,178,'congo',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Cook Islands','CK','COK',NULL,184,'cook-islands',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Costa Rica','CR','CRI',NULL,188,'costa-rica',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Cote dIvoire','CI','CIV',NULL,384,'cote-divoire',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Croatia','HR','HRV',NULL,191,'croatia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Cuba','CU','CUB',NULL,192,'cuba',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Cyprus','CY','CYP',NULL,196,'cyprus',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Czech Republic','CZ','CZE',NULL,203,'czech-republic',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Democratic Republic of the Congo','CD','COD',NULL,180,'democratic-republic-of-congo',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Denmark','DK','DNK',NULL,208,'denmark',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Djibouti','DJ','DJI',NULL,262,'djibouti',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Dominica','DM','DMA',NULL,212,'dominica',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Dominican Republic','DO','DOM',NULL,214,'dominican-republic',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Ecuador','EC','ECU',NULL,218,'ecuador',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Egypt','EG','EGY',NULL,818,'egypt',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('El Salvador','SV','SLV',NULL,222,'el-salvador',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Equatorial Guinea','GQ','GNQ',NULL,226,'equatorial-guinea',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Eritrea','ER','ERI',NULL,232,'eritrea',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Estonia','EE','EST',NULL,233,'estonia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Ethiopia','ET','ETH',NULL,231,'ethiopia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Faeroe Islands','FO','FRO',NULL,234,'faeroe-islands',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Falkland Islands','FK','FLK',NULL,238,'falkland-islands',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Fiji','FJ','FJI',NULL,242,'fiji',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Finland','FI','FIN',NULL,246,'finland',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('France','FR','FRA',NULL,250,'france',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('French Guiana','GF','GUF',NULL,254,'french-guiana',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('French Polynesia','PF','PYF',NULL,258,'french-polynesia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Gabon','GA','GAB',NULL,266,'gabon',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Gambia','GM','GMB',NULL,270,'gambia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Georgia','GE','GEO',NULL,268,'georgia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Germany','DE','DEU',NULL,276,'germany',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Ghana','GH','GHA',NULL,288,'ghana',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Gibraltar','GI','GIB',NULL,292,'gibraltar',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Greece','GR','GRC',NULL,300,'greece',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Greenland','GL','GRL',NULL,304,'greenland',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Grenada','GD','GRD',NULL,308,'grenada',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Guadeloupe','GP','GLP',NULL,312,'guadeloupe',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Guam','GU','GUM',NULL,316,'guam',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Guatemala','GT','GTM',NULL,320,'guatemala',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Guernsey','GG','GGY',NULL,831,'guernsey',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Guinea','GN','GIN',NULL,324,'guinea',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Guinea-Bissau','GW','GNB',NULL,624,'guinea-bissau',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Guyana','GY','GUY',NULL,328,'guyana',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Haiti','HT','HTI',NULL,332,'haiti',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Holy See','VA','VAT',NULL,336,'holy-see',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Honduras','HN','HND',NULL,340,'honduras',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Hong Kong','HK','HKG',NULL,344,'hong-kong',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Hungary','HU','HUN',NULL,348,'hungary',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Iceland','IS','ISL',NULL,352,'iceland',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('India','IN','IND',NULL,356,'india',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Indonesia','ID','IDN',NULL,360,'indonesia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Iran','IR','IRN',NULL,364,'iran',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Iraq','IQ','IRQ',NULL,368,'iraq',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Ireland','IE','IRL',NULL,372,'ireland',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Isle of Man','IM','IMN',NULL,833,'isle-of-man',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Israel','IL','ISR',NULL,376,'israel',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Italy','IT','ITA',NULL,380,'italy',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Jamaica','JM','JAM',NULL,388,'jamaica',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Japan','JP','JPN',NULL,392,'japan',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Jersey','JE','JEY',NULL,832,'jersey',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Jordan','JO','JOR',NULL,400,'jordan',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Kazakhstan','KZ','KAZ',NULL,398,'kazakhstan',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Kenya','KE','KEN',NULL,404,'kenya',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Kiribati','KI','KIR',NULL,296,'kiribati',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Kuwait','KW','KWT',NULL,414,'kuwait',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Kyrgyzstan','KG','KGZ',NULL,417,'kyrgyzstan',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Laos','LA','LAO',NULL,418,'laos',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Latvia','LV','LVA',NULL,428,'latvia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Lebanon','LB','LBN',NULL,422,'lebanon',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Lesotho','LS','LSO',NULL,426,'lesotho',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Liberia','LR','LBR',NULL,430,'liberia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Libyan Arab Jamahiriya','LY','LBY',NULL,434,'libyan-arab-jamahiriya',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Liechtenstein','LI','LIE',NULL,438,'liechtenstein',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Lithuania','LT','LTU',NULL,440,'lithuania',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Luxembourg','LU','LUX',NULL,442,'luxembourg',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Macao','MO','MAC',NULL,446,'macao',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Macedonia','MK','MKD',NULL,807,'macedonia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Madagascar','MG','MDG',NULL,450,'madagascar',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Malawi','MW','MWI',NULL,454,'malawi',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Malaysia','MY','MYS',NULL,458,'malaysia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Maldives','MV','MDV',NULL,462,'maldives',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Mali','ML','MLI',NULL,466,'mali',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Malta','MT','MLT',NULL,470,'malta',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Marshall Islands','MH','MHL',NULL,584,'marshall-islands',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Martinique','MQ','MTQ',NULL,474,'martinique',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Mauritania','MR','MRT',NULL,478,'mauritania',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Mauritius','MU','MUS',NULL,480,'mauritius',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Mayotte','YT','MYT',NULL,175,'mayotte',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Mexico','MX','MEX',NULL,484,'mexico',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Micronesia','FM','FSM',NULL,583,'micronesia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Moldova','MD','MDA',NULL,498,'moldova',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Monaco','MC','MCO',NULL,492,'monaco',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Mongolia','MN','MNG',NULL,496,'mongolia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Montenegro','ME','MNE',NULL,499,'montenegro',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Montserrat','MS','MSR',NULL,500,'montserrat',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Morocco','MA','MAR',NULL,504,'morocco',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Mozambique','MZ','MOZ',NULL,508,'mozambique',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Myanmar','MM','MMR','BUR',104,'myanmar',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Namibia','NA','NAM',NULL,516,'namibia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Nauru','NR','NRU',NULL,520,'nauru',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Nepal','NP','NPL',NULL,524,'nepal',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Netherlands','NL','NLD',NULL,528,'netherlands',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Netherlands Antilles','AN','ANT',NULL,530,'netherlands-antilles',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('New Caledonia','NC','NCL',NULL,540,'new-caledonia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('New Zealand','NZ','NZL',NULL,554,'new-zealand',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Nicaragua','NI','NIC',NULL,558,'nicaragua',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Niger','NE','NER',NULL,562,'niger',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Nigeria','NG','NGA',NULL,566,'nigeria',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Niue','NU','NIU',NULL,570,'niue',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Norfolk Island','NF','NFK',NULL,574,'norfolk-island',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('North Korea','KP','PRK',NULL,408,'north-korea',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Northern Mariana Islands','MP','MNP',NULL,580,'northern-mariana-islands',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Norway','NO','NOR',NULL,578,'norway',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Oman','OM','OMN',NULL,512,'oman',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Pakistan','PK','PAK',NULL,586,'pakistan',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Palau','PW','PLW',NULL,585,'palau',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Palestine','PS','PSE',NULL,275,'palestine',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Panama','PA','PAN',NULL,591,'panama',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Papua New Guinea','PG','PNG',NULL,598,'papua-new-guinea',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Paraguay','PY','PRY',NULL,600,'paraguay',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Peru','PE','PER',NULL,604,'peru',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Philippines','PH','PHL',NULL,608,'philippines',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Pitcairn','PN','PCN',NULL,612,'pitcairn',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Poland','PL','POL',NULL,616,'poland',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Portugal','PT','PRT',NULL,620,'portugal',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Puerto Rico','PR','PRI',NULL,630,'puerto-rico',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Qatar','QA','QAT',NULL,634,'qatar',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Reunion','RE','REU',NULL,638,'reunion',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Romania','RO','ROU','ROM',642,'romania',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Russian Federation','RU','RUS',NULL,643,'russian-federation',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Rwanda','RW','RWA',NULL,646,'rwanda',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Saint Helena','SH','SHN',NULL,654,'saint-helena',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Saint Kitts and Nevis','KN','KNA',NULL,659,'saint-kitts-and-nevis',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Saint Lucia','LC','LCA',NULL,662,'saint-lucia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Saint Pierre and Miquelon','PM','SPM',NULL,666,'saint-pierre-and-miquelon',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Saint Vincent and the Grenadines','VC','VCT',NULL,670,'saint-vincent-and-grenadines',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Saint-Barthelemy','BL','BLM',NULL,652,'saint-barthelemy',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Saint-Martin','MF','MAF',NULL,663,'saint-martin',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Samoa','WS','WSM',NULL,882,'samoa',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('San Marino','SM','SMR',NULL,674,'san-marino',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Sao Tome and Principe','ST','STP',NULL,678,'sao-tome-and-principe',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Saudi Arabia','SA','SAU',NULL,682,'saudi-arabia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Senegal','SN','SEN',NULL,686,'senegal',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Serbia','RS','SRB',NULL,688,'serbia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Seychelles','SC','SYC',NULL,690,'seychelles',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Sierra Leone','SL','SLE',NULL,694,'sierra-leone',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Singapore','SG','SGP',NULL,702,'singapore',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Slovakia','SK','SVK',NULL,703,'slovakia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Slovenia','SI','SVN',NULL,705,'slovenia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Solomon Islands','SB','SLB',NULL,90,'solomon-islands',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Somalia','SO','SOM',NULL,706,'somalia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('South Africa','ZA','ZAF',NULL,710,'south-africa',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('South Korea','KR','KOR',NULL,410,'south-korea',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('South Sudan','SS','SSD',NULL,728,'south-sudan',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Spain','ES','ESP',NULL,724,'spain',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Sri Lanka','LK','LKA',NULL,144,'sri-lanka',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Sudan','SD','SDN',NULL,729,'sudan',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Suriname','SR','SUR',NULL,740,'suriname',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Svalbard and Jan Mayen Islands','SJ','SJM',NULL,744,'svalbard-and-jan-mayen-islands',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Swaziland','SZ','SWZ',NULL,748,'swaziland',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Sweden','SE','SWE',NULL,752,'sweden',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Switzerland','CH','CHE',NULL,756,'switzerland',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Syrian Arab Republic','SY','SYR',NULL,760,'syrian-arab-republic',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Tajikistan','TJ','TJK',NULL,762,'tajikistan',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Tanzania','TZ','TZA',NULL,834,'tanzania',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Thailand','TH','THA',NULL,764,'thailand',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Timor-Leste','TP','TLS',NULL,626,'timor-leste',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Togo','TG','TGO',NULL,768,'togo',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Tokelau','TK','TKL',NULL,772,'tokelau',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Tonga','TO','TON',NULL,776,'tonga',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Trinidad and Tobago','TT','TTO',NULL,780,'trinidad-and-tobago',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Tunisia','TN','TUN',NULL,788,'tunisia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Turkey','TR','TUR',NULL,792,'turkey',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Turkmenistan','TM','TKM',NULL,795,'turkmenistan',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Turks and Caicos Islands','TC','TCA',NULL,796,'turks-and-caicos-islands',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Tuvalu','TV','TUV',NULL,798,'tuvalu',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('U.S. Virgin Islands','VI','VIR',NULL,850,'us-virgin-islands',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Uganda','UG','UGA',NULL,800,'uganda',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Ukraine','UA','UKR',NULL,804,'ukraine',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('United Arab Emirates','AE','ARE',NULL,784,'united-arab-emirates',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('United Kingdom','UK','GBR',NULL,826,'united-kingdom',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('United States','US','USA',NULL,840,'united-states',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Uruguay','UY','URY',NULL,858,'uruguay',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Uzbekistan','UZ','UZB',NULL,860,'uzbekistan',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Vanuatu','VU','VUT',NULL,548,'vanuatu',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Venezuela','VE','VEN',NULL,862,'venezuela',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Viet Nam','VN','VNM',NULL,704,'viet-nam',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Wallis and Futuna Islands','WF','WLF',NULL,876,'wallis-and-futuna-islands',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Western Sahara','EH','ESH',NULL,732,'western-sahara',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Yemen','YE','YEM',NULL,887,'yemen',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Zambia','ZM','ZMB',NULL,894,'zambia',UUID());
INSERT INTO "countries" ("name","abv","abv3","abv3_alt","code","slug","uuid") VALUES('Zimbabwe','ZW','ZWE',NULL,716,'zimbabwe',UUID());